modLoader = "javafml"
loaderVersion = "[44,)"
license = "All Rights Reserved"
[[mods]]
modId = "dpr"
version = "${file.jarVersion}"
displayName = "Dark Prince's Realm"
description = '''

'''

[[dependencies.dpr]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.dpr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"
